[env:esp32-poe]
platform = espressif32
board = esp32-poe
framework = arduino
monitor_speed = 115200

lib_deps =
    adafruit/Adafruit SSD1306
    adafruit/Adafruit GFX Library
    # Add an LLDP or Packet Sniffing library here later